In [ ]:
# for dataframe analysis and manipulation.
import pandas as pd
import numpy as np
import regex as re

# for data preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer

# for model Building
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# for removing stopwords
from nltk.corpus import stopwords
stop = stopwords.words('english')

#!python -m nltk.downloader stopwords

# Loading the dataset

In [ ]:
df = pd.read_table('SpamCollection.txt', names = ['Label', 'Message'])
df.head()

     Label                                            Message
0  no_spam  Go until jurong point, a crazy.. Available onl...
1  no_spam                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3  no_spam  U dun say so early hor... U c already then say...
4  no_spam  Nah I don't think he goes to usf, he lives aro...

## About the dataset

- The dataset contains labeled emaols, where each mail is classified as spam. It has both the email text and corresponding labels

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Label    5572 non-null   str
 1   Message  5572 non-null   str
dtypes: str(2)
memory usage: 87.2 KB

## Analysis 

- There are no messing value in the dataset
- The target value is in categorical form

# Data Preparation

## Incoding target variable

In [ ]:
le = LabelEncoder()
df['Label'] = le.fit_transform(df['Label'])

In [ ]:
df.head()

   Label                                            Message
0      0  Go until jurong point, a crazy.. Available onl...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

## Data Cleaning

In [ ]:
def data_cleaning(text):
    text = str(text).lower()
    text = re.sub('[^a-z]', ' ',  text)
    words = text.split()
    imp_words = [word for word in words if word not in stop]
    return ' '.join(imp_words)

In [ ]:
df['Message'] = df['Message'].apply(lambda x: data_cleaning(x))
# lambda est une fct anonime qui permet d'appliquer une fonction à chaque élément d'une série ou d'une colonne d'un DataFrame. Ici, elle est utilisée pour appliquer la fonction data_cleaning à chaque message de la colonne 'Message' du DataFrame df.

In [ ]:
df.head()

   Label                                            Message
0      0  go jurong point crazy available bugis n great ...
1      0                            ok lar joking wif u oni
2      1  free entry wkly comp win fa cup final tkts st ...
3      0                u dun say early hor u c already say
4      0             nah think goes usf lives around though

## Train test split

In [ ]:
X = df['Message']
y = df['Label']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

## Feature extraction

- Converting the text data into numerical features using countvectoriser

In [ ]:
df.Message.head()

0    go jurong point crazy available bugis n great ...
1                              ok lar joking wif u oni
2    free entry wkly comp win fa cup final tkts st ...
3                  u dun say early hor u c already say
4               nah think goes usf lives around though
Name: Message, dtype: str

In [ ]:
cv = CountVectorizer()
# CountVectorizer est une classe de la bibliothèque scikit-learn qui convertit une collection de documents textuels en une matrice de caractéristiques numériques. Chaque ligne de la matrice représente un document, et chaque colonne représente un mot unique dans l'ensemble des documents. La valeur dans chaque cellule indique le nombre d'occurrences du mot correspondant dans le document correspondant.

X_train = cv.fit_transform(X_train)
X_test = cv.transform(X_test)

# fit_transform() est utilisé pour ajuster le CountVectorizer aux données d'entraînement et transformer ces données en une matrice de caractéristiques. transform() est utilisé pour transformer les données de test en utilisant le même CountVectorizer ajusté sur les données d'entraînement.

In [ ]:
Indexes = pd.DataFrame(X_train.toarray(), columns=cv.get_feature_names_out())
print(cv.vocabulary_)

{'one': 4012, 'good': 2333, 'partnership': 4155, 'going': 2321, 'take': 5734, 'lead': 3174, 'sounds': 5385, 'like': 3231, 'something': 5355, 'someone': 5350, 'testing': 5825, 'would': 6598, 'sayy': 4984, 'want': 6377, 'new': 3847, 'nokia': 3892, 'colour': 1092, 'phone': 4252, 'deliveredtomorrow': 1420, 'free': 2143, 'minutes': 3600, 'mobile': 3640, 'texts': 5839, 'camcorder': 822, 'reply': 4767, 'call': 807, 'ugh': 6138, 'leg': 3191, 'hurts': 2696, 'musta': 3755, 'overdid': 4087, 'mon': 3662, 'urgent': 6215, 'trying': 6085, 'contact': 1169, 'todays': 5976, 'draw': 1618, 'shows': 5188, 'prize': 4469, 'guaranteed': 2412, 'land': 3125, 'line': 3244, 'claim': 1015, 'valid': 6258, 'hrs': 2665, 'erm': 1800, 'thought': 5898, 'contract': 1178, 'ran': 4620, 'th': 5843, 'october': 3967, 'dont': 1582, 'know': 3091, 'come': 1099, 'ask': 329, 'questions': 4586, 'mistake': 3617, 'wine': 6516, 'flowing': 2073, 'nevering': 3845, 'please': 4313, 'give': 2297, 'us': 6226, 'connection': 1160, 'today': 5975, 'lt': 3362, 'decimal': 1388, 'gt': 2408, 'refund': 4708, 'bill': 568, 'cos': 1206, 'daddy': 1330, 'arranging': 310, 'time': 5936, 'wat': 6392, 'fetch': 1984, 'mah': 3414, 'farm': 1943, 'open': 4027, 'jason': 2927, 'says': 4983, 'cool': 1190, 'pick': 4264, 'place': 4293, 'hour': 2648, 'hey': 2561, 'congrats': 1155, 'id': 2724, 'luv': 3379, 'ive': 2902, 'go': 2313, 'home': 2612, 'uworld': 6249, 'site': 5244, 'buying': 786, 'qbank': 4570, 'self': 5055, 'assessment': 340, 'also': 176, 'collect': 1085, 'ur': 6211, 'laptop': 3139, 'dear': 1377, 'reach': 4644, 'ok': 3991, 'enjoy': 1770, 'dinner': 1507, 'ah': 121, 'well': 6447, 'confuses': 1154, 'things': 5878, 'doesnt': 1565, 'friends': 2163, 'maybe': 3500, 'wrong': 6618, 'thing': 5877, 'already': 173, 'sort': 5377, 'invited': 2859, 'tho': 5895, 'may': 3498, 'money': 3665, 'chat': 934, 'awesome': 402, 'make': 3427, 'regular': 4721, 'unless': 6184, 'see': 5039, 'person': 4225, 'kano': 3024, 'whr': 6490, 'treat': 6058, 'maga': 3408, 'lets': 3209, 'thank': 5846, 'god': 2315, 'complete': 1123, 'drug': 1641, 'lots': 3330, 'water': 6398, 'beautiful': 499, 'day': 1366, 'likely': 3233, 'called': 811, 'mittelschmertz': 3621, 'google': 2345, 'paracetamol': 4133, 'worry': 6588, 'escape': 1809, 'theatre': 5856, 'watch': 6393, 'kavalan': 3031, 'hello': 2544, 'boytoy': 677, 'geeee': 2252, 'missing': 3611, 'send': 5066, 'tm': 5961, 'remind': 4742, 'thinking': 5882, 'loved': 3342, 'loving': 3351, 'kiss': 3079, 'much': 3730, 'get': 2270, 'got': 2351, 'back': 422, 'dislikes': 1534, 'bed': 507, 'many': 3451, 'company': 1114, 'tell': 5799, 'language': 3134, 'dude': 1655, 'sux': 5679, 'snake': 5319, 'old': 4002, 'raiden': 4606, 'buff': 752, 'wait': 6354, 'lor': 3320, 'need': 3813, 'feel': 1970, 'bad': 424, 'lar': 3140, 'march': 3456, 'ending': 1757, 'ready': 4654, 'sure': 5666, 'problem': 4474, 'capital': 838, 'never': 3844, 'far': 1942, 'work': 6577, 'ladies': 3116, 'said': 4929, 'eat': 1689, 'shit': 5151, 'morning': 3683, 'pa': 4103, 'gud': 2414, 'mrng': 3712, 'hav': 2504, 'nice': 3860, 'quite': 4591, 'still': 5535, 'hold': 2603, 'anyone': 238, 'cud': 1291, 'bout': 668, 'pm': 4325, 'pub': 4536, 'though': 5897, 'understand': 6164, 'important': 2768, 'put': 4561, 'poorly': 4359, 'punishment': 4546, 'face': 1911, 'worst': 6591, 'ever': 1835, 'happened': 2477, 'brb': 690, 'gonna': 2331, 'kill': 3066, 'bookedthe': 644, 'hut': 2700, 'way': 6409, 'jus': 3002, 'finish': 2025, 'watching': 6397, 'tv': 6108, 'poop': 4357, 'looks': 3313, 'ill': 2748, 'prob': 4472, 'fixed': 2044, 'cuz': 1322, 'gpu': 2364, 'huh': 2677, 'lesson': 3206, 'lei': 3195, 'thinkin': 5881, 'sch': 4992, 'earlier': 1676, 'tot': 6020, 'parkin': 4148, 'kent': 3043, 'vale': 6255, 'meeting': 3527, 'welp': 6449, 'semiobscure': 5064, 'internet': 2848, 'landline': 3127, 'abta': 21, 'complimentary': 1127, 'tenerife': 5811, 'holiday': 2607, 'cash': 870, 'await': 396, 'collection': 1088, 'sae': 4923, 'cs': 1276, 'box': 671, 'cw': 1323, 'wx': 6635, 'ppm': 4400, 'entry': 1789, 'wkly': 6546, 'comp': 1111, 'win': 6508, 'fa': 1908, 'cup': 1301, 'final': 2015, 'tkts': 5958, 'st': 5476, 'text': 5829, 'receive': 4677, 'question': 4584, 'std': 5515, 'txt': 6120, 'rate': 4628, 'apply': 265, 'last': 3146, 'weekends': 6434, 'code': 1071, 'mind': 3586, 'bedroom': 510, 'minute': 3599, 'sed': 5038, 'sexy': 5102, 'mood': 3677, 'came': 823, 'minuts': 3601, 'latr': 3154, 'wid': 6495, 'cake': 799, 'wife': 6498, 'looking': 3312, 'job': 2958, 'ta': 5720, 'earn': 1679, 'somebody': 5348, 'set': 5090, 'website': 6424, 'play': 4305, 'em': 1738, 'using': 6238, 'eve': 1828, 'online': 4016, 'spacebucks': 5394, 'yeah': 6677, 'impression': 2775, 'darling': 1350, 'love': 3341, 'look': 3309, 'na': 3767, 'second': 5028, 'half': 2454, 'message': 3557, 'coughing': 1217, 'nothing': 3918, 'girl': 2291, 'hope': 2627, 'del': 1411, 'bak': 431, 'long': 3305, 'sum': 5637, 'lucyxx': 3372, 'bull': 760, 'plan': 4296, 'floating': 2066, 'ikea': 2743, 'without': 6536, 'care': 847, 'world': 6583, 'live': 3269, 'mess': 3556, 'another': 224, 'wot': 6595, 'bitch': 585, 'bit': 584, 'smile': 5303, 'hppnss': 2662, 'drop': 1636, 'tear': 5786, 'sorrow': 5374, 'part': 4150, 'heart': 2528, 'life': 3224, 'mine': 3587, 'wil': 6503, 'forevr': 2109, 'goodfriend': 2335, 'winner': 6519, 'valued': 6261, 'network': 3839, 'customer': 1313, 'hvae': 2702, 'selected': 5053, 'reward': 4821, 'hours': 2649, 'acl': 43, 'oh': 3986, 'mr': 3710, 'sheffield': 5133, 'wanna': 6375, 'game': 2221, 'okay': 3992, 'boss': 659, 'nanny': 3781, 'raise': 4610, 'ic': 2716, 'meant': 3514, 'mary': 3472, 'jane': 2922, 'delivered': 1419, 'tomorrow': 5995, 'wipro': 6525, 'interview': 2849, 'book': 642, 'msg': 3716, 'sth': 5531, 'specs': 5418, 'membership': 3542, 'px': 4568, 'success': 5621, 'slow': 5288, 'biola': 576, 'fne': 2080, 'okie': 3995, 'takes': 5737, 'wrc': 6605, 'rally': 4617, 'oz': 4102, 'lucozade': 3370, 'energy': 1763, 'le': 3173, 'packs': 4107, 'co': 1060, 'uk': 6143, 'itcould': 2892, 'ha': 2440, 'nan': 3779, 'yalrigu': 6665, 'heltini': 2551, 'iyo': 2905, 'kothi': 3104, 'chikku': 974, 'shared': 5125, 'wit': 6534, 'told': 5985, 'body': 632, 'even': 1830, 'uttered': 6244, 'word': 6575, 'abt': 20, 'trusting': 6081, 'others': 4066, 'plz': 4324, 'nxt': 3950, 'use': 6230, 'words': 6576, 'think': 5879, 'late': 3148, 'school': 4994, 'night': 3868, 'especially': 1813, 'class': 1023, 'missed': 3609, 'wednesday': 6428, 'probably': 4473, 'failed': 1919, 'test': 5824, 'friday': 2158, 'wow': 6601, 'thats': 5853, 'gay': 2242, 'firmware': 2033, 'update': 6199, 'help': 2546, 'private': 4467, 'account': 36, 'statement': 5505, 'un': 6150, 'redeemed': 4697, 'points': 4338, 'identifier': 2729, 'expires': 1890, 'add': 60, 'really': 4662, 'least': 3182, 'fuck': 2185, 'hate': 2499, 'didnt': 1481, 'accept': 27, 'single': 5233, 'messaged': 3558, 'eh': 1719, 'wrongly': 6619, 'ruin': 4898, 'thesis': 5868, 'voucher': 6339, 'holder': 2604, 'airport': 131, 'lounge': 3338, 'passes': 4163, 'booking': 645, 'quote': 4596, 'thanks': 5847, 'visa': 6317, 'coming': 1104, 'gucci': 2413, 'bags': 427, 'sister': 5241, 'easy': 1688, 'uncle': 6155, 'john': 2965, 'bills': 571, 'later': 3151, 'sha': 5108, 'dint': 1509, 'slept': 5277, 'afternoon': 107, 'pee': 4195, 'burns': 771, 'tonite': 6002, 'cold': 1080, 'sad': 4922, 'nt': 3931, 'yet': 6691, 'simple': 5223, 'habba': 2441, 'hw': 2703, 'babe': 413, 'everything': 1844, 'alrite': 175, 'idiot': 2731, 'girlie': 2293, 'costa': 1209, 'sol': 5342, 'toclaim': 5974, 'tc': 5773, 'pobox': 4329, 'stockport': 5540, 'sk': 5254, 'xh': 6643, 'cost': 1208, 'max': 3495, 'mins': 3596, 'dollars': 1576, 'hi': 2565, 'guess': 2418, 'needa': 3814, 'mcat': 3504, 'study': 5593, 'bbq': 483, 'sat': 4963, 'ish': 2883, 'welcome': 6445, 'congratulations': 1157, 'awarded': 400, 'either': 1724, 'yrs': 6718, 'supply': 5659, 'cds': 892, 'virgin': 6314, 'records': 4691, 'mystery': 3766, 'gift': 2284, 'ts': 6086, 'www': 6634, 'smsco': 5314, 'net': 3833, 'approx': 275, 'pleased': 4314, 'advise': 88, 'following': 2088, 'recent': 4681, 'review': 4819, 'mob': 3638, 'bonus': 639, 'mm': 3627, 'yes': 6688, 'hugging': 2674, 'offer': 3974, 'worth': 6592, 'discount': 1529, 'vouchers': 6340, 'savamob': 4974, 'member': 3540, 'offers': 3977, 'sub': 5606, 'unsub': 6192, 'literally': 3266, 'mths': 3724, 'oranges': 4047, 'latest': 3152, 'camera': 824, 'mobiles': 3641, 'unlimited': 6186, 'weekend': 6433, 'calls': 819, 'upd': 6197, 'freefone': 2146, 'stoptxt': 5554, 'next': 3855, 'da': 1326, 'horrible': 2637, 'macs': 3400, 'forgot': 2114, 'rite': 4846, 'thk': 5888, 'toot': 6008, 'prepared': 4433, 'shall': 5118, 'husband': 2697, 'lovely': 3344, 'drinkin': 1626, 'dancin': 1339, 'eatin': 1691, 'cinema': 1009, 'check': 943, 'rooms': 4873, 'befor': 517, 'activities': 54, 'freemsg': 2149, 'indicate': 2803, 'entitled': 1787, 'pounds': 4391, 'accident': 29, 'opt': 4040, 'stop': 5546, 'always': 181, 'available': 386, 'screaming': 5012, 'means': 3513, 'shouting': 5178, 'sunshine': 5648, 'dawns': 1365, 'refreshed': 4707, 'happy': 2484, 'alive': 160, 'breathe': 698, 'air': 130, 'early': 1678, 'bird': 577, 'purchases': 4552, 'webpage': 6423, 'thanx': 5850, 'yup': 6728, 'sun': 5642, 'hotel': 2646, 'flies': 2057, 'tog': 5978, 'exactly': 1859, 'mth': 3723, 'haf': 2444, 'dunno': 1664, 'shd': 5130, 'driving': 1633, 'hr': 2663, 'oni': 4014, 'rent': 4753, 'expensive': 1884, 'save': 4975, 'asking': 333, 'gym': 2437, 'excuse': 1867, 'lazy': 3167, 'people': 4204, 'jog': 2963, 'healthy': 2522, 'rd': 4642, 'cant': 836, 'anything': 241, 'else': 1735, 'bathing': 471, 'dog': 1566, 'working': 6580, 'bored': 654, 'etc': 1820, 'ring': 4836, 'nose': 3912, 'essay': 1815, 'xx': 6649, 'sorry': 5376, 'battery': 475, 'died': 1483, 'getting': 2277, 'gram': 2370, 'link': 3250, 'picture': 4270, 'sent': 5075, 'http': 2667, 'alto': 180, 'wave': 6405, 'asp': 337, 'splashmobile': 5441, 'choose': 995, 'gr': 2365, 'tones': 5998, 'wk': 6542, 'subscrition': 5619, 'service': 5086, 'weekly': 6435, 'costing': 1210, 'credit': 1253, 'kick': 3057, 'guys': 2434, 'forwarded': 2126, 'mailbox': 3420, 'messaging': 3560, 'sms': 5313, 'alert': 148, 'matches': 3480, 'retrieve': 4809, 'messages': 3559, 'cc': 888, 'min': 3584, 'coco': 1070, 'birthdate': 581, 'certificate': 905, 'april': 278, 'real': 4655, 'date': 1358, 'publish': 4538, 'special': 5411, 'keep': 3037, 'secret': 5030, 'wishes': 6530, 'short': 5168, 'cute': 1318, 'try': 6083, 'prove': 4518, 'rock': 4855, 'yr': 6717, 'chik': 973, 'filthy': 2013, 'films': 2011, 'xxx': 6652, 'pics': 4268, 'rply': 4885, 'filth': 2012, 'saristar': 4959, 'ltd': 3363, 'yt': 6720, 'per': 4206, 'days': 1367, 'cancel': 831, 'sir': 5239, 'waiting': 6357, 'mail': 3419, 'competition': 1118, 'txttowin': 6128, 'let': 3208, 'noe': 3886, 'details': 1453, 'frnd': 2170, 'necesity': 3806, 'imagine': 2756, 'urself': 6225, 'witout': 6539, 'colleg': 1089, 'wth': 6625, 'cell': 899, 'functions': 2197, 'thnk': 5892, 'events': 1833, 'espe': 1812, 'cared': 849, 'amp': 198, 'irritated': 2876, 'wrd': 6606, 'frnds': 2171, 'wthout': 6626, 'jst': 2988, 'takecare': 5735, 'goodmorning': 2338, 'unbelievable': 6152, 'faglord': 1918, 'xmas': 6645, 'iscoming': 2882, 'cd': 890, 'music': 3752, 'tnc': 5968, 'ldew': 3170, 'com': 1095, 'ppmx': 4404, 'age': 112, 'subscription': 5616, 'great': 2388, 'office': 3978, 'damn': 1335, 'tonight': 6000, 'til': 5934, 'seen': 5047, 'im': 2752, 'arestaurant': 290, 'eating': 1692, 'squid': 5471, 'dosomething': 1595, 'able': 13, 'meet': 3525, 'within': 6535, 'actually': 57, 'leave': 3183, 'house': 2650, 'hospital': 2640, 'return': 4810, 'evening': 1831, 'maid': 3418, 'murderer': 3749, 'coz': 1234, 'man': 3437, 'murdered': 3748, 'january': 2923, 'public': 4537, 'govt': 2362, 'instituitions': 2835, 'closed': 1043, 'including': 2786, 'post': 4378, 'missy': 3615, 'group': 2401, 'mate': 3481, 'lucky': 3369, 'havent': 2508, 'maaaan': 3391, 'faith': 1924, 'makes': 3428, 'possible': 4376, 'three': 5904, 'christmas': 1003, 'merry': 3554, 'sunday': 5643, 'diet': 1485, 'flew': 2056, 'window': 6512, 'imma': 2760, 'definitely': 1406, 'restock': 4801, 'thanksgiving': 5848, 'gran': 2372, 'onlyfound': 4018, 'afew': 94, 'ago': 119, 'cusoon': 1309, 'honi': 2619, 'left': 3189, 'dessert': 1450, 'wan': 6373, 'suntec': 5649, 'shaking': 5117, 'booty': 651, 'dance': 1338, 'floor': 2068, 'smoking': 5311, 'wylie': 6636, 'smokes': 5309, 'justify': 3005, 'ruining': 4899, 'xchat': 6640, 'attempt': 364, 'middle': 3571, 'right': 4833, 'ride': 4832, 'remember': 4737, 'ben': 537, 'settled': 5094, 'room': 4869, 'orchard': 4049, 'near': 3803, 'univ': 6180, 'family': 1933, 'rhode': 4826, 'island': 2885, 'wherever': 6479, 'leaving': 3185, 'alone': 170, 'week': 6432, 'bong': 638, 'reaching': 4647, 'lot': 3328, 'restocked': 4802, 'hard': 2485, 'connect': 1158, 'cheap': 938, 'biggest': 567, 'vu': 6344, 'bcm': 487, 'wc': 6411, 'denying': 1433, 'lost': 3327, 'since': 5228, 'doc': 1554, 'visit': 6319, 'woot': 6571, 'celebrate': 895, 'stuffing': 5598, 'cooked': 1187, 'rather': 4630, 'salmon': 4937, 'la': 3110, 'contacted': 1170, 'dating': 1361, 'entered': 1780, 'fancy': 1937, 'find': 2019, 'tf': 5840, 'fine': 2022, 'hows': 2658, 'london': 3303, 'treatin': 6060, 'ya': 6662, 'treacle': 6056, 'railway': 4607, 'pay': 4181, 'lakhs': 3121, 'first': 2035, 'answer': 227, 'lol': 3299, 'happens': 2480, 'vegas': 6275, 'stays': 5513, 'asked': 331, 'waheeda': 6351, 'fathima': 1951, 'sleeping': 5272, 'took': 6005, 'zaher': 6730, 'ym': 6698, 'miss': 3608, 'exam': 1860, 'film': 2010, 'juz': 3008, 'search': 5023, 'qet': 4571, 'reached': 4646, 'bathe': 470, 'liao': 3215, 'bishan': 583, 'nearer': 3804, 'buy': 783, 'gotta': 2358, 'park': 4146, 'car': 843, 'stories': 5558, 'girls': 2294, 'haircut': 2450, 'breezy': 702, 'sooooo': 5372, 'wish': 6528, 'sleep': 5270, 'lonely': 3304, 'dream': 1620, 'fun': 2195, 'chance': 913, 'remove': 4748, 'notice': 3919, 'weeks': 6436, 'anyway': 243, 'plans': 4302, 'garage': 2229, 'keys': 3050, 'bookshelf': 648, 'tone': 5997, 'every': 1836, 'txting': 6123, 'mates': 3482, 'getzed': 2278, 'wq': 6603, 'norm': 3906, 'gd': 2248, 'shopping': 5166, 'stuff': 5596, 'infernal': 2807, 'affairs': 96, 'surly': 5671, 'fall': 1928, 'prone': 4506, 'falls': 1930, 'dad': 1329, 'yar': 6669, 'mum': 3739, 'lunch': 3374, 'whole': 6486, 'stay': 5509, 'clean': 1029, 'hee': 2536, 'bluray': 625, 'player': 4307, 'request': 4774, 'maangalyam': 3392, 'alaipayuthe': 143, 'callertune': 814, 'callers': 813, 'press': 4446, 'copy': 1197, 'telling': 5800, 'kindly': 3073, 'documents': 1561, 'submitted': 5609, 'loan': 3284, 'stapati': 5490, 'ages': 116, 'abj': 12, 'ahhh': 124, 'vaguely': 6254, 'superior': 5653, 'dai': 1332, 'naal': 3768, 'eruku': 1804, 'alfie': 153, 'moon': 3678, 'children': 978, 'song': 5362, 'charity': 925, 'nokias': 3893, 'poly': 4345, 'polys': 4350, 'zed': 6731, 'profit': 4489, 'rubber': 4894, 'loads': 3283, 'loans': 3285, 'claire': 1018, 'havin': 2510, 'borin': 655, 'cum': 1298, 'nite': 3879, 'minmoremobsemspobox': 3593, 'po': 4328, 'wa': 6345, 'goldviking': 2325, 'inviting': 2860, 'friend': 2162, 'ac': 24, 'antibiotic': 235, 'used': 6231, 'chest': 963, 'abdomen': 7, 'gynae': 2439, 'infections': 2806, 'bone': 637, 'goin': 2320, 'soon': 5367, 'mountain': 3699, 'deer': 1400, 'show': 5181, 'yo': 6700, 'tickets': 5925, 'jacket': 2911, 'done': 1580, 'multis': 3738, 'themob': 5861, 'comes': 1101, 'selection': 5054, 'hot': 2645, 'downloads': 1606, 'members': 3541, 'click': 1037, 'fone': 2091, 'six': 5252, 'chances': 914, 'csh': 1278, 'tsandcs': 6087, 'hl': 2586, 'info': 2808, 'sry': 5474, 'knw': 3095, 'siva': 5251, 'tats': 5760, 'askd': 330, 'tht': 5915, 'incident': 2782, 'present': 4441, 'ar': 282, 'whatever': 6469, 'better': 550, 'costume': 1212, 'end': 1755, 'flat': 2052, 'female': 1981, 'throwing': 5910, 'deciding': 1387, 'gal': 2216, 'mc': 3502, 'videophones': 6300, 'videochat': 6299, 'java': 2928, 'games': 2222, 'dload': 1550, 'polyh': 4347, 'noline': 3894, 'rentl': 4756, 'bx': 791, 'ip': 2865, 'kate': 3029, 'jackson': 2913, 'rec': 4673, 'center': 900, 'almost': 169, 'mca': 3503, 'conform': 1152, 'infront': 2813, 'chuckin': 1005, 'red': 4696, 'green': 2392, 'black': 591, 'trainners': 6042, 'carryin': 865, 'bac': 421, 'train': 6039, 'wana': 6374, 'trip': 6066, 'sometme': 5358, 'must': 3754, 'walk': 6360, 'everywhere': 1846, 'cannot': 835, 'tram': 6044, 'cousin': 1230, 'vic': 6294, 'market': 3462, 'ned': 3812, 'convince': 1184, 'witot': 6538, 'hurting': 2695, 'feeling': 1972, 'main': 3423, 'agree': 120, 'ipad': 2866, 'macho': 3397, 'birth': 580, 'lb': 3168, 'mother': 3693, 'baby': 416, 'brilliantly': 710, 'lucy': 3371, 'hubby': 2670, 'meetins': 3528, 'fri': 2157, 'cumin': 1299, 'pls': 4320, 'minmobsmorelkpobox': 3592, 'hp': 2661, 'fl': 2047, 'compass': 1116, 'map': 3452, 'soul': 5383, 'guide': 2424, 'loose': 3317, 'gnun': 2312, 'via': 6290, 'skyped': 5265, 'kz': 3109, 'sura': 5665, 'pleasure': 4315, 'given': 2298, 'ultimatum': 6146, 'countin': 1221, 'aburo': 22, 'generally': 2257, 'uncountable': 6161, 'noun': 3923, 'dictionary': 1479, 'pieces': 4274, 'research': 4778, 'talk': 5742, 'jerry': 2944, 'cartoon': 868, 'irritates': 2877, 'loves': 3349, 'vry': 6342, 'fails': 1921, 'express': 1898, 'nyt': 3954, 'unredeemed': 6188, 'ee': 1708, 'poortiyagi': 4360, 'odalebeku': 3968, 'hanumanji': 2474, 'name': 3776, 'hanuman': 2473, 'bajarangabali': 430, 'maruti': 3471, 'pavanaputra': 4180, 'sankatmochan': 4948, 'ramaduth': 4618, 'mahaveer': 3416, 'janarige': 2921, 'ivatte': 2901, 'kalisidare': 3018, 'saturday': 4971, 'olage': 3999, 'ondu': 4011, 'news': 3852, 'keluviri': 3041, 'maretare': 3457, 'inde': 2795, 'dodda': 1562, 'problum': 4478, 'nalli': 3775, 'siguviri': 5216, 'idu': 2734, 'matra': 3487, 'true': 6077, 'neglet': 3824, 'information': 2810, 'birthday': 582, 'praveesh': 4419, 'log': 3292, 'number': 3938, 'delicious': 1417, 'sky': 5263, 'dark': 1346, 'raining': 4609, 'run': 4906, 'alex': 152, 'knows': 3094, 'fifteen': 1995, 'concerned': 1139, 'brainless': 682, 'doll': 1575, 'vehicle': 6278, 'sariyag': 4960, 'drive': 1630, 'madoke': 3404, 'barolla': 455, 'completely': 1125, 'form': 2117, 'clark': 1021, 'utter': 6243, 'waste': 6390, 'ringtone': 4839, 'pw': 4567, 'nd': 3800, 'thursday': 5919, 'yay': 6675, 'cheers': 952, 'alright': 174, 'holding': 2605, 'tightly': 5930, 'making': 3431, 'mean': 3509, 'absolutely': 18, 'south': 5389, 'recently': 4682, 'started': 5498, 'actual': 56, 'harder': 2487, 'nbme': 3799, 'wake': 6358, 'truth': 6082, 'gravity': 2383, 'read': 4650, 'carefully': 853, 'feels': 1975, 'light': 3228, 'heavy': 2534, 'leaves': 3184, 'studying': 5594, 'thurs': 5918, 'unsold': 6190, 'panren': 4125, 'paru': 4158, 'super': 5651, 'replacement': 4764, 'murali': 3746, 'textbuddy': 5832, 'horny': 2636, 'area': 288, 'postcode': 4380, 'gaytextbuddy': 2244, 'appt': 277, 'fault': 1954, 'listen': 3260, 'twice': 6112, 'booked': 643, 'kb': 3034, 'lessons': 3207, 'confirm': 1149, 'lodging': 3291, 'rose': 4875, 'blood': 614, 'tis': 5949, 'poor': 4358, 'relation': 4723, 'support': 5660, 'luvs': 3381, 'praying': 4421, 'marry': 3470, 'seeing': 5041, 'lotta': 3333, 'corvettes': 1205, 'lately': 3149, 'langport': 3133, 'sucks': 5624, 'sri': 5472, 'lanka': 3135, 'stress': 5568, 'rcv': 4640, 'msgs': 3720, 'svc': 5681, 'hardcore': 2486, 'services': 5087, 'verify': 6285, 'clarify': 1020, 'ticket': 5924, 'preponed': 4435, 'kerala': 3045, 'iam': 2708, 'knew': 3088, 'murder': 3747, 'buzzzz': 790, 'grins': 2396, 'buzz': 789, 'ass': 339, 'cock': 1068, 'vibrator': 6293, 'shake': 5116, 'big': 565, 'meaning': 3510, 'best': 545, 'yep': 6686, 'ice': 2718, 'balance': 434, 'landmark': 3130, 'bob': 631, 'barry': 458, 'luck': 3367, 'waaaat': 6346, 'lololo': 3301, 'paper': 4130, 'top': 6012, 'british': 718, 'hotels': 2647, 'sw': 5682, 'ss': 5475, 'wonder': 6562, 'smiling': 5306, 'crazy': 1247, 'away': 401, 'bugis': 755, 'dun': 1662, 'passport': 4166, 'smth': 5317, 'dat': 1356, 'email': 1739, 'tried': 6065, 'textand': 5830, 'video': 6298, 'delivery': 1421, 'bus': 774, 'aft': 105, 'lect': 3186, 'a

In [ ]:
occurences = pd.DataFrame(X_train.toarray(), columns=cv.get_feature_names_out())
print(occurences)

      aa  aah  aaniye  aaooooright  aathi  ab  abbey  abdomen  aberdeen  abi  \
0      0    0       0            0      0   0      0        0         0    0
1      0    0       0            0      0   0      0        0         0    0
2      0    0       0            0      0   0      0        0         0    0
3      0    0       0            0      0   0      0        0         0    0
4      0    0       0            0      0   0      0        0         0    0
...   ..  ...     ...          ...    ...  ..    ...      ...       ...  ...
4452   0    0       0            0      0   0      0        0         0    0
4453   0    0       0            0      0   0      0        0         0    0
4454   0    0       0            0      0   0      0        0         0    0
4455   0    0       0            0      0   0      0        0         0    0
4456   0    0       0            0      0   0      0        0         0    0

      ...  yuou  yup  yupz  zaher  zed  zhong  zoe  zoom  zouk  zs
0     ...     0    0     0      0    0      0    0     0     0   0
1     ...     0    0     0      0    0      0    0     0     0   0
2     ...     0    0     0      0    0      0    0     0     0   0
3     ...     0    0     0      0    0      0    0     0     0   0
4     ...     0    0     0      0    0      0    0     0     0   0
...   ...   ...  ...   ...    ...  ...    ...  ...   ...   ...  ..
4452  ...     0    0     0      0    0      0    0     0     0   0
4453  ...     0    0     0      0    0      0    0     0     0   0
4454  ...     0    0     0      0    0      0    0     0     0   0
4455  ...     0    0     0      0    0      0    0     0     0   0
4456  ...     0    0     0      0    0      0    0     0     0   0

[4457 rows x 6737 columns]

# Model Training

In [ ]:
# Model Training
multi_nb = MultinomialNB()
multi_nb.fit(X_train, y_train)

MultinomialNB()

MultinomialNB()

In [ ]:
# Model Evaluation
y_pred = multi_nb.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

# Print scores
print("Accuracy:", round(accuracy, 4))
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", report)

Accuracy: 0.9919

Confusion Matrix:
 [[966   4]
 [  5 140]]

Classification Report:
               precision    recall  f1-score   support

           0       0.99      1.00      1.00       970
           1       0.97      0.97      0.97       145

    accuracy                           0.99      1115
   macro avg       0.98      0.98      0.98      1115
weighted avg       0.99      0.99      0.99      1115

# Conclusion

# Prediction on sample data